- name: Hardening
  hosts: all
  remote_user: sysadmin
  become: yes
  vars:
    sysctl_overwrite:
      net.ipv4.ip_forward: 1
    network_ipv6_enable: false
    ssh_server_ports: ['2222']
    ssh_client_port: '2222'
  
  collections:
  - devsec.hardening

  roles:
    - role: devsec.hardening.os_hardening
      state: present

    - role: devsec.hardening.ssh_hardening
      state: present